vich_uploader:
    db_driver: orm

#    mappings:
#        miniature_produit:
#            uri_prefix: /uploads/produit
#            # Dossier d'upload
#            upload_destination: '%kernel.project_dir%/public/uploads/produit